### ISSUE TITLE
Release Checklist - v2.0.0

### ISSUE THREAD

**Issue by TonyGrif** [TonyGrif/pdf-finder#17]
Tasks pertaining to the next major release

## Features
- [x] #18 
- [x] #19 

## Refactor
- [ ] Better exporting of finder functions and classes
- [ ] Module level logger

## Docs
- [ ] Own project site

## Build
- [ ] Automatic publishing to PyPi on tag
